### ISSUE TITLE
Error: Expected "payload" to be a plain object.

### ISSUE THREAD

**Issue by vijoytechy** [bradtraversy/nodeauthapp#3]
**Hello brad,**
I was following your tutorial from youtube, and while running authentication in postman Iam getting error that `Error: Expected "payload" to be a plain object. at validate (/home/vijo/Music/MeanLearn/node_modules/jsonwebtoken/sign.js:34:11) at validatePayload (/home/vijo/Music/MeanLearn/node_modules/jsonwebtoken/sign.js:56:10) at Object.module.exports [as sign] (/home/vijo/Music/MeanLearn/node_modules/jsonwebtoken/sign.js:108:7) at User.comparePassword (/home/vijo/Music/MeanLearn/routes/users.js:41:33) at bcrypt.compare (/home/vijo/Music/MeanLearn/models/user.js:46:9) at /home/vijo/Music/MeanLearn/node_modules/bcryptjs/dist/bcrypt.js:297:21 at /home/vijo/Music/MeanLearn/node_modules/bcryptjs/dist/bcrypt.js:1353:21 at Immediate.next [as _onImmediate] (/home/vijo/Music/MeanLearn/node_modules/bcryptjs/dist/bcrypt.js:1233:21) at runCallback (timers.js:789:20) at tryOnImmediate (timers.js:751:5) at processImmediate [as _immediateCallback] (timers.js:722:5)`
# **Please help me to resolve this**
**passport.js**
```
`const JwtStrategy = require('passport-jwt').Strategy;
const ExtractJwt = require('passport-jwt').ExtractJwt;
const User = require('../models/user');
const config = require('../config/database');

module.exports = function(passport){
let opts = {};
opts.jwtFromRequest = ExtractJwt.fromAuthHeaderWithScheme("jwt");
opts.secretOrKey = config.secret;
passport.use(new JwtStrategy(opts, (jwt_payload, done) => {
User.getUserById(jwt_payload.data._id, (err, user) => {
if(err){
return done(err, false);
}

  if(user){
    return done(null, user);
  } else {
    return done(null, false);
  }
});
}));
}`
```

**Comment by grugknuckle** [comment]
I think this line may be the issue ....

`User.getUserById(jwt_payload.data._id, (err, user) => {
...
}`

I think it should be 'jwt_payload._id' instead of 'jwt_payload.data._id'

**Comment by vijoytechy** [comment]
@grugknuckle I tried to print on console its getting same error
`const JwtStrategy = require('passport-jwt').Strategy;
const ExtractJwt = require('passport-jwt').ExtractJwt;
const User = require('../models/user');
const config = require('../config/database');

module.exports = function(passport){
  let opts = {};
  opts.jwtFromRequest = ExtractJwt.fromAuthHeaderWithScheme("jwt");
  opts.secretOrKey = config.secret;
  passport.use(new JwtStrategy(opts, (jwt_payload, done) => {
	console.log(jwt_payload);
    User.getUserById(jwt_payload.users._id, (err, user) => {
      if(err){
        return done(err, false);
      }

      if(user){
        return done(null, user);
      } else {
        return done(null, false);
      }
    });
  }));
}
`

**Comment by grugknuckle** [comment]
@vijoytechy The error you've posted is being thrown by the 'jsonwebtoken' library. That library isn't referenced in the passport.js file you've posted. It's happening in your routes/users.js file at the '/authenticate' endpoint. Something is wrong there. In Brad's project, I see this [users.js](https://github.com/bradtraversy/nodeauthapp/blob/master/routes/users.js) file. At around line 40 in that code is where the 'jsonwebtoken' library is signing the token. For your code, the equivalent line is where the error is happening.

**Comment by singhalok641** [comment]
I have resolved this issue. Shall I make a pull request ?

**Comment by Capitanbasa** [comment]
this issue is already resolve. check again the https://github.com/bradtraversy/nodeauthapp/blob/master/config/passport.js

**Comment by sushil50889** [comment]
It fails at the line.
`const token = jwt.sign(user, config.secret, {`

With error "Expected "payload" to be a plain object".
Your `user` object is initialized here:

`User.getUserByUsername(username, (err, user)`

Which I assume is mongoosejs object, which contains many methods and is not "serializable". You could handle this by passing a plain object, by either using .lean() from mongoose or plain toJSON method:

```
const token = jwt.sign(user.toJSON(), config.secret, {
  expiresIn: 604800 // 1 week
});
```

**Comment by Capitanbasa** [comment]
this work for me 

`// Authenticate
router.post('/authenticate', (req, res, next) => {
  const username = req.body.username;
  const password = req.body.password;

  User.getUserByUsername(username, (err, user) => {
    if(err) throw err;
    if(!user){
      return res.json({success: false, msg: 'User not found'});
    }

    User.comparePassword(password, user.password, (err, isMatch) => {
      if(err) throw err;
      if(isMatch){
        const token = jwt.sign({data: user}, config.secret, {
          expiresIn: 604800 // 1 week
        });

        res.json({
          success: true,
          token: 'JWT '+token,
          user: {
            id: user._id,
            name: user.name,
            username: user.username,
            email: user.email
          }
        });
      } else {
        return res.json({success: false, msg: 'Wrong password'});
      }
    });
  });
});`

**Comment by Jay007lord** [comment]
Your payload  may be an Object but when  you want to send that to mongodb then you should change that object to plain object.  Convert object to plain object you should use following method. object=object.toObject() 

If you get _id isn't find error then change something in your code.
Inside
  User.getUserById(jwt_payload.data._id, (err, user) => { ... })
change
 jwt_payload._id instead of jwt_payload.data._id.

**Comment by munapadhi** [comment]
const token = jwt.sign({data: user}, config.secret, {
      expiresIn: 604800 // 1 week
    });

i have only change {data>user} its works for me

**Comment by vijoytechy** [comment]
`const JwtStrategy = require('passport-jwt').Strategy;
const ExtractJwt = require('passport-jwt').ExtractJwt;
const User = require('../models/user');
const config = require('../config/database');

module.exports = function(passport) {
  let opts = {};
  opts.jwtFromRequest = ExtractJwt.fromAuthHeaderWithScheme('jwt');
  opts.secretOrKey = config.secret;
  passport.use(new JwtStrategy(opts, (jwt_payload, done) => {
    User.getUserById(jwt_payload.data._id, (err, user) => {
      if(err) {
        return done(err, false);
      }

      if(user) {
        return done(null, user);
      } else {
        return done(null, false);
      }
    });
  }));
}`

**Comment by JappanBhavsar003** [comment]
Just change this code to this:

` const token = jwt.sign(user.toJSON(), config.secret, {
                    expiresIn: 604800  // 1 Week
                });`

and boom it works now :)

**Comment by TharakaWickramarathna** [comment]
> It fails at the line.
> `const token = jwt.sign(user, config.secret, {`
> 
> With error "Expected "payload" to be a plain object".
> Your `user` object is initialized here:
> 
> `User.getUserByUsername(username, (err, user)`
> 
> Which I assume is mongoosejs object, which contains many methods and is not "serializable". You could handle this by passing a plain object, by either using .lean() from mongoose or plain toJSON method:
> 
> ```
> const token = jwt.sign(user.toJSON(), config.secret, {
>   expiresIn: 604800 // 1 week
> });
> ```

fixed...Thank you for helping us...!

**Comment by jonathandestinec** [comment]
Use this

```js
jwt.verify({user}, {expiresIn: 604800}
```

The payload you're passing has to be in json format, so you can do tuat by surrounding it with `{}`
